### ISSUE TITLE
Enable spellcheck by default?

### ISSUE THREAD

**Issue by reinink** [vovkkk/sublime_git_syntaxes#3]
Love this package, great work on it. Quick question, would it be possible to enable the spell checker by default whenever doing a commit, or other similar Git actions that require input. Spelling mistakes are easy to make, and enabling this by default would be awesome!

**Comment by vovkkk** [comment]
Create files:
1. For commits `Packages/User/commit-message.sublime-settings`
2. For rebase `Packages/User/rebase.sublime-settings`

Content of those files:

``` json
{
    "spell_check": true
}
```

You also can add any setting you want (different colour scheme, font face, font size, rulers, word wrap, etc.).

**Comment by reinink** [comment]
Amazing. Thanks!
